### ISSUE TITLE
More details in Readme.md file

### ISSUE THREAD

**Issue by maheshwarimrinal** [mish1102/Extract-Possible-Titles-from-Sentence#1]
Can you add more details in `Readme.md` file about how your algorithm works or how can we use it, so that it is easy for us to understand the working and flow of it and we can think of use cases for the same in our project.

Thanks :)

**Comment by mish1102** [comment]
> Can you add more details in `Readme.md` file about how your algorithm works or how can we use it, so that it is easy for us to understand the working and flow of it and we can think of use cases for the same in our project.
> 
> Thanks :)

Hi @maheshwarimrinal , Thanks for your query. The README.md is updated now. Have a look at the same. If you have any query regarding the algorithm design, feel free to connect through my email mimansha02@gmail.com. 

Highly appreciated. 

Best Always!

**Comment by mish1102** [comment]
> Can you add more details in `Readme.md` file about how your algorithm works or how can we use it, so that it is easy for us to understand the working and flow of it and we can think of use cases for the same in our project.
> 
> Thanks :)

Hi @maheshwarimrinal  , Thank you for your query. The README.md is updated now. Have a look at the same. If you have any queries regarding the algorithm design, feel free to reach out to me on my emailID:  mimansha02@gmail.com.

Highly appreciated.

Best Always!
